// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using myNotesApi.Models;

namespace myNotesApi.Migrations
{
    [DbContext(typeof(myNotesApiContext))]
    partial class myNotesApiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("myNotesApi.Models.NoteItem", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("noteInfo");

                    b.Property<string>("title");

                    b.HasKey("id");

                    b.ToTable("NoteItem");
                });
#pragma warning restore 612, 618
        }
    }
}
